name: Deploy to planethoster
on:
  push:
    tags:
      - "v*"
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v2
      - run: bun i
      - run: PUBLIC_PATH=https://pierrelespingal.xyz/app/earth/${{ github.ref_name }}/ bun run build-example
      - run: PUBLIC_PATH=https://pierrelespingal.xyz/app/earth/${{ github.ref_name }}/ bun run build
      - run: |
          cd build/lib
          mkdir ../package
          npm pack --pack-destination ../package

      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          local-dir: ./build/
          server-dir: ./app/earth/${{ github.ref_name }}/
          server: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          dry-run: ${{ env.ACT }}
