name: Deploy to planethoster
on:
  push:
    tags:
      - "v*"
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run build -- --output-public-path https://app.pierrelespingal.xyz/earth/${{ github.ref_name }}/
      - run: |
          cd dist/lib
          mkdir ../package
          npm pack --pack-destination ../package
      - uses: appleboy/scp-action@v0.1.7
        with:
          source: "dist/*"
          target: app/earth/${{ github.ref_name }}
          rm: true
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
